// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddModelData, AddModelErrors, AddModelResponses, CreateKeyData, CreateKeyErrors, CreateKeyResponses, DeleteKeyData, DeleteKeyErrors, DeleteKeyResponses, DeleteModelData, DeleteModelErrors, DeleteModelResponses, DeleteOauthData, DeleteOauthErrors, DeleteOauthResponses, DeleteUsageHistoryData, DeleteUsageHistoryErrors, DeleteUsageHistoryResponses, ExchangeOauthCodeData, ExchangeOauthCodeErrors, ExchangeOauthCodeResponses, GetKeyModelsData, GetKeyModelsResponses, GetKeyModelUsageData, GetKeyModelUsageResponses, GetKeyUsageData, GetKeyUsageErrors, GetKeyUsageResponses, GetOauthStatusData, GetOauthStatusResponses, GetSubscriptionUsageData, GetSubscriptionUsageErrors, GetSubscriptionUsageResponses, GetUsageHistoryByKeyData, GetUsageHistoryByKeyResponses, GetUsageHistoryByModelData, GetUsageHistoryByModelResponses, GetUsageHistoryTimeseriesData, GetUsageHistoryTimeseriesResponses, ListKeysData, ListKeysResponses, ListModelsAdminData, ListModelsAdminResponses, RemoveKeyModelLimitsData, RemoveKeyModelLimitsErrors, RemoveKeyModelLimitsResponses, ReorderModelsData, ReorderModelsErrors, ReorderModelsResponses, ResetKeyModelUsageData, ResetKeyModelUsageErrors, ResetKeyModelUsageResponses, ResetKeyUsageData, ResetKeyUsageErrors, ResetKeyUsageResponses, SetAllowExtraUsageData, SetAllowExtraUsageErrors, SetAllowExtraUsageResponses, SetKeyEnabledData, SetKeyEnabledErrors, SetKeyEnabledResponses, SetKeyModelLimitsData, SetKeyModelLimitsErrors, SetKeyModelLimitsResponses, SetKeyModelsData, SetKeyModelsErrors, SetKeyModelsResponses, StartOauthFlowData, StartOauthFlowResponses, UpdateKeyLimitsData, UpdateKeyLimitsErrors, UpdateKeyLimitsResponses, UpdateModelData, UpdateModelErrors, UpdateModelResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new API key
 */
export const createKey = <ThrowOnError extends boolean = false>(options: Options<CreateKeyData, ThrowOnError>) => (options.client ?? client).post<CreateKeyResponses, CreateKeyErrors, ThrowOnError>({
    url: '/keys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all API keys
 */
export const listKeys = <ThrowOnError extends boolean = false>(options?: Options<ListKeysData, ThrowOnError>) => (options?.client ?? client).get<ListKeysResponses, unknown, ThrowOnError>({ url: '/keys/list', ...options });

/**
 * Delete an API key
 */
export const deleteKey = <ThrowOnError extends boolean = false>(options: Options<DeleteKeyData, ThrowOnError>) => (options.client ?? client).delete<DeleteKeyResponses, DeleteKeyErrors, ThrowOnError>({ url: '/keys/{id}', ...options });

/**
 * Toggle allow_extra_usage for a key
 */
export const setAllowExtraUsage = <ThrowOnError extends boolean = false>(options: Options<SetAllowExtraUsageData, ThrowOnError>) => (options.client ?? client).put<SetAllowExtraUsageResponses, SetAllowExtraUsageErrors, ThrowOnError>({
    url: '/keys/{id}/allow-extra-usage',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Toggle a key enabled/disabled
 */
export const setKeyEnabled = <ThrowOnError extends boolean = false>(options: Options<SetKeyEnabledData, ThrowOnError>) => (options.client ?? client).put<SetKeyEnabledResponses, SetKeyEnabledErrors, ThrowOnError>({
    url: '/keys/{id}/enabled',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update limits for a key
 */
export const updateKeyLimits = <ThrowOnError extends boolean = false>(options: Options<UpdateKeyLimitsData, ThrowOnError>) => (options.client ?? client).put<UpdateKeyLimitsResponses, UpdateKeyLimitsErrors, ThrowOnError>({
    url: '/keys/{id}/limits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get per-model usage for a key
 */
export const getKeyModelUsage = <ThrowOnError extends boolean = false>(options: Options<GetKeyModelUsageData, ThrowOnError>) => (options.client ?? client).get<GetKeyModelUsageResponses, unknown, ThrowOnError>({ url: '/keys/{id}/model-usage', ...options });

/**
 * Remove per-model limits for a key
 */
export const removeKeyModelLimits = <ThrowOnError extends boolean = false>(options: Options<RemoveKeyModelLimitsData, ThrowOnError>) => (options.client ?? client).delete<RemoveKeyModelLimitsResponses, RemoveKeyModelLimitsErrors, ThrowOnError>({ url: '/keys/{id}/model-usage/{model}/limits', ...options });

/**
 * Set per-model limits for a key
 */
export const setKeyModelLimits = <ThrowOnError extends boolean = false>(options: Options<SetKeyModelLimitsData, ThrowOnError>) => (options.client ?? client).put<SetKeyModelLimitsResponses, SetKeyModelLimitsErrors, ThrowOnError>({
    url: '/keys/{id}/model-usage/{model}/limits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset per-model usage counters for a key
 */
export const resetKeyModelUsage = <ThrowOnError extends boolean = false>(options: Options<ResetKeyModelUsageData, ThrowOnError>) => (options.client ?? client).post<ResetKeyModelUsageResponses, ResetKeyModelUsageErrors, ThrowOnError>({
    url: '/keys/{id}/model-usage/{model}/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get allowed models for a key
 */
export const getKeyModels = <ThrowOnError extends boolean = false>(options: Options<GetKeyModelsData, ThrowOnError>) => (options.client ?? client).get<GetKeyModelsResponses, unknown, ThrowOnError>({ url: '/keys/{id}/models', ...options });

/**
 * Set allowed models for a key (empty = allow all)
 */
export const setKeyModels = <ThrowOnError extends boolean = false>(options: Options<SetKeyModelsData, ThrowOnError>) => (options.client ?? client).put<SetKeyModelsResponses, SetKeyModelsErrors, ThrowOnError>({
    url: '/keys/{id}/models',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get usage statistics for a key
 */
export const getKeyUsage = <ThrowOnError extends boolean = false>(options: Options<GetKeyUsageData, ThrowOnError>) => (options.client ?? client).get<GetKeyUsageResponses, GetKeyUsageErrors, ThrowOnError>({ url: '/keys/{id}/usage', ...options });

/**
 * Reset usage counters for a key
 */
export const resetKeyUsage = <ThrowOnError extends boolean = false>(options: Options<ResetKeyUsageData, ThrowOnError>) => (options.client ?? client).post<ResetKeyUsageResponses, ResetKeyUsageErrors, ThrowOnError>({
    url: '/keys/{id}/usage/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all models (admin sees enabled + disabled)
 */
export const listModelsAdmin = <ThrowOnError extends boolean = false>(options?: Options<ListModelsAdminData, ThrowOnError>) => (options?.client ?? client).get<ListModelsAdminResponses, unknown, ThrowOnError>({ url: '/models', ...options });

/**
 * Add a new model
 */
export const addModel = <ThrowOnError extends boolean = false>(options: Options<AddModelData, ThrowOnError>) => (options.client ?? client).post<AddModelResponses, AddModelErrors, ThrowOnError>({
    url: '/models',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reorder models
 */
export const reorderModels = <ThrowOnError extends boolean = false>(options: Options<ReorderModelsData, ThrowOnError>) => (options.client ?? client).put<ReorderModelsResponses, ReorderModelsErrors, ThrowOnError>({
    url: '/models/reorder',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a model
 */
export const deleteModel = <ThrowOnError extends boolean = false>(options: Options<DeleteModelData, ThrowOnError>) => (options.client ?? client).delete<DeleteModelResponses, DeleteModelErrors, ThrowOnError>({ url: '/models/{id}', ...options });

/**
 * Update a model (prices, enabled)
 */
export const updateModel = <ThrowOnError extends boolean = false>(options: Options<UpdateModelData, ThrowOnError>) => (options.client ?? client).put<UpdateModelResponses, UpdateModelErrors, ThrowOnError>({
    url: '/models/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete OAuth credentials
 */
export const deleteOauth = <ThrowOnError extends boolean = false>(options?: Options<DeleteOauthData, ThrowOnError>) => (options?.client ?? client).delete<DeleteOauthResponses, DeleteOauthErrors, ThrowOnError>({ url: '/oauth', ...options });

/**
 * Exchange OAuth code
 */
export const exchangeOauthCode = <ThrowOnError extends boolean = false>(options: Options<ExchangeOauthCodeData, ThrowOnError>) => (options.client ?? client).post<ExchangeOauthCodeResponses, ExchangeOauthCodeErrors, ThrowOnError>({
    url: '/oauth/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start OAuth flow
 */
export const startOauthFlow = <ThrowOnError extends boolean = false>(options?: Options<StartOauthFlowData, ThrowOnError>) => (options?.client ?? client).post<StartOauthFlowResponses, unknown, ThrowOnError>({ url: '/oauth/start-flow', ...options });

/**
 * Get OAuth connection status
 */
export const getOauthStatus = <ThrowOnError extends boolean = false>(options?: Options<GetOauthStatusData, ThrowOnError>) => (options?.client ?? client).get<GetOauthStatusResponses, unknown, ThrowOnError>({ url: '/oauth/status', ...options });

/**
 * Get Claude subscription usage from Anthropic API
 */
export const getSubscriptionUsage = <ThrowOnError extends boolean = false>(options?: Options<GetSubscriptionUsageData, ThrowOnError>) => (options?.client ?? client).get<GetSubscriptionUsageResponses, GetSubscriptionUsageErrors, ThrowOnError>({ url: '/oauth/usage', ...options });

export const deleteUsageHistory = <ThrowOnError extends boolean = false>(options?: Options<DeleteUsageHistoryData, ThrowOnError>) => (options?.client ?? client).delete<DeleteUsageHistoryResponses, DeleteUsageHistoryErrors, ThrowOnError>({ url: '/usage-history', ...options });

export const getUsageHistoryByKey = <ThrowOnError extends boolean = false>(options?: Options<GetUsageHistoryByKeyData, ThrowOnError>) => (options?.client ?? client).get<GetUsageHistoryByKeyResponses, unknown, ThrowOnError>({ url: '/usage-history/by-key', ...options });

export const getUsageHistoryByModel = <ThrowOnError extends boolean = false>(options?: Options<GetUsageHistoryByModelData, ThrowOnError>) => (options?.client ?? client).get<GetUsageHistoryByModelResponses, unknown, ThrowOnError>({ url: '/usage-history/by-model', ...options });

export const getUsageHistoryTimeseries = <ThrowOnError extends boolean = false>(options?: Options<GetUsageHistoryTimeseriesData, ThrowOnError>) => (options?.client ?? client).get<GetUsageHistoryTimeseriesResponses, unknown, ThrowOnError>({ url: '/usage-history/timeseries', ...options });
