// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateKeyData, CreateKeyErrors, CreateKeyResponses, DeleteKeyData, DeleteKeyErrors, DeleteKeyResponses, DeleteOauthData, DeleteOauthErrors, DeleteOauthResponses, ExchangeOauthCodeData, ExchangeOauthCodeErrors, ExchangeOauthCodeResponses, GetKeyUsageData, GetKeyUsageErrors, GetKeyUsageResponses, GetOauthStatusData, GetOauthStatusResponses, ListKeysData, ListKeysResponses, ResetKeyUsageData, ResetKeyUsageErrors, ResetKeyUsageResponses, StartOauthFlowData, StartOauthFlowResponses, UpdateKeyLimitsData, UpdateKeyLimitsErrors, UpdateKeyLimitsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new API key
 */
export const createKey = <ThrowOnError extends boolean = false>(options: Options<CreateKeyData, ThrowOnError>) => (options.client ?? client).post<CreateKeyResponses, CreateKeyErrors, ThrowOnError>({
    url: '/keys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all API keys
 */
export const listKeys = <ThrowOnError extends boolean = false>(options?: Options<ListKeysData, ThrowOnError>) => (options?.client ?? client).get<ListKeysResponses, unknown, ThrowOnError>({ url: '/keys/list', ...options });

/**
 * Delete an API key
 */
export const deleteKey = <ThrowOnError extends boolean = false>(options: Options<DeleteKeyData, ThrowOnError>) => (options.client ?? client).delete<DeleteKeyResponses, DeleteKeyErrors, ThrowOnError>({ url: '/keys/{id}', ...options });

/**
 * Update limits for a key
 */
export const updateKeyLimits = <ThrowOnError extends boolean = false>(options: Options<UpdateKeyLimitsData, ThrowOnError>) => (options.client ?? client).put<UpdateKeyLimitsResponses, UpdateKeyLimitsErrors, ThrowOnError>({
    url: '/keys/{id}/limits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get usage statistics for a key
 */
export const getKeyUsage = <ThrowOnError extends boolean = false>(options: Options<GetKeyUsageData, ThrowOnError>) => (options.client ?? client).get<GetKeyUsageResponses, GetKeyUsageErrors, ThrowOnError>({ url: '/keys/{id}/usage', ...options });

/**
 * Reset usage counters for a key
 */
export const resetKeyUsage = <ThrowOnError extends boolean = false>(options: Options<ResetKeyUsageData, ThrowOnError>) => (options.client ?? client).post<ResetKeyUsageResponses, ResetKeyUsageErrors, ThrowOnError>({
    url: '/keys/{id}/usage/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete OAuth credentials
 */
export const deleteOauth = <ThrowOnError extends boolean = false>(options?: Options<DeleteOauthData, ThrowOnError>) => (options?.client ?? client).delete<DeleteOauthResponses, DeleteOauthErrors, ThrowOnError>({ url: '/oauth', ...options });

/**
 * Exchange OAuth code
 */
export const exchangeOauthCode = <ThrowOnError extends boolean = false>(options: Options<ExchangeOauthCodeData, ThrowOnError>) => (options.client ?? client).post<ExchangeOauthCodeResponses, ExchangeOauthCodeErrors, ThrowOnError>({
    url: '/oauth/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start OAuth flow
 */
export const startOauthFlow = <ThrowOnError extends boolean = false>(options?: Options<StartOauthFlowData, ThrowOnError>) => (options?.client ?? client).post<StartOauthFlowResponses, unknown, ThrowOnError>({ url: '/oauth/start-flow', ...options });

/**
 * Get OAuth connection status
 */
export const getOauthStatus = <ThrowOnError extends boolean = false>(options?: Options<GetOauthStatusData, ThrowOnError>) => (options?.client ?? client).get<GetOauthStatusResponses, unknown, ThrowOnError>({ url: '/oauth/status', ...options });
