// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4096' | (string & {});
};

export type ClientKey = {
    createdAt: number;
    enabled: boolean;
    id: string;
    key: string;
    lastUsedAt?: number | null;
    /**
     * Token usage limits (optional)
     */
    limits?: TokenLimits;
    name: string;
    /**
     * Current token usage
     */
    usage?: TokenUsage;
};

export type CreateKeyRequest = {
    name: string;
};

export type CreateKeyResponse = {
    id: string;
    key: string;
};

export type ErrorResponse = {
    error: string;
};

export type ExchangeCodeRequest = {
    code: string;
};

export type KeyUsageResponse = {
    limits: TokenLimits;
    usage: TokenUsage;
};

export type ListKeysResponse = {
    keys: Array<ClientKey>;
};

export type OAuthStatusResponse = {
    authenticated: boolean;
};

export type OAuthUrlResponse = {
    url: string;
};

export type ResetUsageRequest = {
    /**
     * Which counter to reset: "hourly", "weekly", "total", or "all"
     */
    type: string;
};

export type SuccessResponse = {
    success: boolean;
};

/**
 * Token usage limits for a client key (all optional)
 */
export type TokenLimits = {
    /**
     * Maximum tokens per hour (None = unlimited)
     */
    hourlyLimit?: number | null;
    /**
     * Maximum total tokens ever (None = unlimited)
     */
    totalLimit?: number | null;
    /**
     * Maximum tokens per week (None = unlimited)
     */
    weeklyLimit?: number | null;
};

/**
 * Current token usage for a client key
 */
export type TokenUsage = {
    /**
     * Timestamp when hourly counter resets (epoch ms)
     */
    hourlyResetAt?: number;
    /**
     * Tokens used in current hour
     */
    hourlyTokens?: number;
    /**
     * Total tokens used (lifetime)
     */
    totalTokens?: number;
    /**
     * Timestamp when weekly counter resets (epoch ms)
     */
    weeklyResetAt?: number;
    /**
     * Tokens used in current week
     */
    weeklyTokens?: number;
};

export type UpdateLimitsRequest = {
    hourlyLimit?: number | null;
    totalLimit?: number | null;
    weeklyLimit?: number | null;
};

export type CreateKeyData = {
    body: CreateKeyRequest;
    path?: never;
    query?: never;
    url: '/keys';
};

export type CreateKeyErrors = {
    400: ErrorResponse;
    500: ErrorResponse;
};

export type CreateKeyError = CreateKeyErrors[keyof CreateKeyErrors];

export type CreateKeyResponses = {
    200: CreateKeyResponse;
};

export type CreateKeyResponse2 = CreateKeyResponses[keyof CreateKeyResponses];

export type ListKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/keys/list';
};

export type ListKeysResponses = {
    200: ListKeysResponse;
};

export type ListKeysResponse2 = ListKeysResponses[keyof ListKeysResponses];

export type DeleteKeyData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}';
};

export type DeleteKeyErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type DeleteKeyError = DeleteKeyErrors[keyof DeleteKeyErrors];

export type DeleteKeyResponses = {
    200: SuccessResponse;
};

export type DeleteKeyResponse = DeleteKeyResponses[keyof DeleteKeyResponses];

export type UpdateKeyLimitsData = {
    body: UpdateLimitsRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/limits';
};

export type UpdateKeyLimitsErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type UpdateKeyLimitsError = UpdateKeyLimitsErrors[keyof UpdateKeyLimitsErrors];

export type UpdateKeyLimitsResponses = {
    200: SuccessResponse;
};

export type UpdateKeyLimitsResponse = UpdateKeyLimitsResponses[keyof UpdateKeyLimitsResponses];

export type GetKeyUsageData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/usage';
};

export type GetKeyUsageErrors = {
    404: ErrorResponse;
};

export type GetKeyUsageError = GetKeyUsageErrors[keyof GetKeyUsageErrors];

export type GetKeyUsageResponses = {
    200: KeyUsageResponse;
};

export type GetKeyUsageResponse = GetKeyUsageResponses[keyof GetKeyUsageResponses];

export type ResetKeyUsageData = {
    body: ResetUsageRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/usage/reset';
};

export type ResetKeyUsageErrors = {
    400: ErrorResponse;
    404: ErrorResponse;
    500: ErrorResponse;
};

export type ResetKeyUsageError = ResetKeyUsageErrors[keyof ResetKeyUsageErrors];

export type ResetKeyUsageResponses = {
    200: SuccessResponse;
};

export type ResetKeyUsageResponse = ResetKeyUsageResponses[keyof ResetKeyUsageResponses];

export type DeleteOauthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth';
};

export type DeleteOauthErrors = {
    500: ErrorResponse;
};

export type DeleteOauthError = DeleteOauthErrors[keyof DeleteOauthErrors];

export type DeleteOauthResponses = {
    200: SuccessResponse;
};

export type DeleteOauthResponse = DeleteOauthResponses[keyof DeleteOauthResponses];

export type ExchangeOauthCodeData = {
    body: ExchangeCodeRequest;
    path?: never;
    query?: never;
    url: '/oauth/exchange';
};

export type ExchangeOauthCodeErrors = {
    400: ErrorResponse;
};

export type ExchangeOauthCodeError = ExchangeOauthCodeErrors[keyof ExchangeOauthCodeErrors];

export type ExchangeOauthCodeResponses = {
    200: SuccessResponse;
};

export type ExchangeOauthCodeResponse = ExchangeOauthCodeResponses[keyof ExchangeOauthCodeResponses];

export type StartOauthFlowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/start-flow';
};

export type StartOauthFlowResponses = {
    200: OAuthUrlResponse;
};

export type StartOauthFlowResponse = StartOauthFlowResponses[keyof StartOauthFlowResponses];

export type GetOauthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/status';
};

export type GetOauthStatusResponses = {
    200: OAuthStatusResponse;
};

export type GetOauthStatusResponse = GetOauthStatusResponses[keyof GetOauthStatusResponses];
