// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4096' | (string & {});
};

export type AddModelRequest = {
    cacheReadPrice?: number;
    cacheWritePrice?: number;
    id: string;
    inputPrice?: number;
    outputPrice?: number;
};

export type ClientKey = {
    allowExtraUsage: boolean;
    createdAt: number;
    enabled: boolean;
    id: string;
    key: string;
    lastUsedAt?: number | null;
    limits?: TokenLimits;
    name: string;
    usage?: TokenUsage;
};

export type CreateKeyRequest = {
    name: string;
};

export type CreateKeyResponse = {
    id: string;
    key: string;
};

export type ErrorResponse = {
    error: string;
};

export type ExchangeCodeRequest = {
    code: string;
};

export type ExtraUsage = {
    is_enabled: boolean;
    monthly_limit?: number | null;
    used_credits?: number | null;
    utilization?: number | null;
};

export type KeyBreakdown = {
    cacheReadTokens: number;
    cacheWriteTokens: number;
    costMicrodollars: number;
    inputTokens: number;
    keyId: string;
    keyName?: string | null;
    outputTokens: number;
    requestCount: number;
};

export type KeyBreakdownResponse = {
    keys: Array<KeyBreakdown>;
    period: string;
};

export type KeyModelUsageResponse = {
    entries: Array<ModelUsageEntry>;
};

export type KeyModelsResponse = {
    allowAll: boolean;
    models: Array<string>;
};

export type KeyUsageResponse = {
    limits: TokenLimits;
    usage: TokenUsage;
};

export type ListKeysResponse = {
    keys: Array<ClientKey>;
};

export type ListModelsResponse = {
    models: Array<Model>;
};

/**
 * A model entry from the database
 */
export type Model = {
    cacheReadPrice: number;
    cacheWritePrice: number;
    enabled: boolean;
    id: string;
    inputPrice: number;
    outputPrice: number;
    sortOrder: number;
};

export type ModelBreakdown = {
    cacheReadTokens: number;
    cacheWriteTokens: number;
    costMicrodollars: number;
    inputTokens: number;
    model: string;
    outputTokens: number;
    requestCount: number;
};

export type ModelBreakdownResponse = {
    models: Array<ModelBreakdown>;
    period: string;
};

/**
 * Per-model usage entry with limits and token breakdowns
 */
export type ModelUsageEntry = {
    fiveHour: TokenBreakdown;
    fiveHourResetAt: number;
    limits: TokenLimits;
    model: string;
    total: TokenBreakdown;
    weekly: TokenBreakdown;
    weeklyResetAt: number;
};

export type OAuthStatusResponse = {
    authenticated: boolean;
    plan?: string | null;
};

export type OAuthUrlResponse = {
    url: string;
};

export type ReorderModelsRequest = {
    ids: Array<string>;
};

export type ResetUsageRequest = {
    /**
     * Which counter to reset: "hourly", "weekly", "total", or "all"
     */
    type: string;
};

export type SetAllowExtraUsageRequest = {
    allow_extra_usage: boolean;
};

export type SetKeyEnabledRequest = {
    enabled: boolean;
};

export type SetKeyModelsRequest = {
    models: Array<string>;
};

export type SubscriptionUsageResponse = {
    extra_usage?: null | ExtraUsage;
    five_hour?: null | UsageLimit;
    seven_day?: null | UsageLimit;
    seven_day_opus?: null | UsageLimit;
    seven_day_sonnet?: null | UsageLimit;
};

export type SuccessResponse = {
    success: boolean;
};

export type TimeseriesPoint = {
    cacheReadTokens: number;
    cacheWriteTokens: number;
    costMicrodollars: number;
    inputTokens: number;
    outputTokens: number;
    requestCount: number;
    timestamp: number;
};

export type TimeseriesResponse = {
    granularity: string;
    period: string;
    points: Array<TimeseriesPoint>;
};

/**
 * 4-type token breakdown for display
 */
export type TokenBreakdown = {
    cacheRead: number;
    cacheWrite: number;
    input: number;
    output: number;
};

/**
 * Token usage limits for a client key (all optional, in microdollars)
 */
export type TokenLimits = {
    /**
     * Maximum cost per 5-hour window (None = unlimited)
     */
    fiveHourLimit?: number | null;
    /**
     * Maximum total cost ever (None = unlimited)
     */
    totalLimit?: number | null;
    /**
     * Maximum cost per week (None = unlimited)
     */
    weeklyLimit?: number | null;
};

/**
 * Current token usage for a client key (derived from per-model aggregation)
 */
export type TokenUsage = {
    /**
     * Timestamp when 5-hour counter resets (epoch ms)
     */
    fiveHourResetAt?: number;
    /**
     * Cost in current 5-hour window (microdollars)
     */
    fiveHourTokens?: number;
    /**
     * Total cost (lifetime, microdollars)
     */
    totalTokens?: number;
    /**
     * Timestamp when weekly counter resets (epoch ms)
     */
    weeklyResetAt?: number;
    /**
     * Cost in current week (microdollars)
     */
    weeklyTokens?: number;
};

export type UpdateLimitsRequest = {
    fiveHourLimit?: number | null;
    totalLimit?: number | null;
    weeklyLimit?: number | null;
};

export type UpdateModelRequest = {
    cacheReadPrice?: number | null;
    cacheWritePrice?: number | null;
    enabled?: boolean | null;
    inputPrice?: number | null;
    outputPrice?: number | null;
};

export type UsageLimit = {
    resets_at?: string | null;
    utilization?: number | null;
};

export type CreateKeyData = {
    body: CreateKeyRequest;
    path?: never;
    query?: never;
    url: '/keys';
};

export type CreateKeyErrors = {
    400: ErrorResponse;
    500: ErrorResponse;
};

export type CreateKeyError = CreateKeyErrors[keyof CreateKeyErrors];

export type CreateKeyResponses = {
    200: CreateKeyResponse;
};

export type CreateKeyResponse2 = CreateKeyResponses[keyof CreateKeyResponses];

export type ListKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/keys/list';
};

export type ListKeysResponses = {
    200: ListKeysResponse;
};

export type ListKeysResponse2 = ListKeysResponses[keyof ListKeysResponses];

export type DeleteKeyData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}';
};

export type DeleteKeyErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type DeleteKeyError = DeleteKeyErrors[keyof DeleteKeyErrors];

export type DeleteKeyResponses = {
    200: SuccessResponse;
};

export type DeleteKeyResponse = DeleteKeyResponses[keyof DeleteKeyResponses];

export type SetAllowExtraUsageData = {
    body: SetAllowExtraUsageRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/allow-extra-usage';
};

export type SetAllowExtraUsageErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type SetAllowExtraUsageError = SetAllowExtraUsageErrors[keyof SetAllowExtraUsageErrors];

export type SetAllowExtraUsageResponses = {
    200: SuccessResponse;
};

export type SetAllowExtraUsageResponse = SetAllowExtraUsageResponses[keyof SetAllowExtraUsageResponses];

export type SetKeyEnabledData = {
    body: SetKeyEnabledRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/enabled';
};

export type SetKeyEnabledErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type SetKeyEnabledError = SetKeyEnabledErrors[keyof SetKeyEnabledErrors];

export type SetKeyEnabledResponses = {
    200: SuccessResponse;
};

export type SetKeyEnabledResponse = SetKeyEnabledResponses[keyof SetKeyEnabledResponses];

export type UpdateKeyLimitsData = {
    body: UpdateLimitsRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/limits';
};

export type UpdateKeyLimitsErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type UpdateKeyLimitsError = UpdateKeyLimitsErrors[keyof UpdateKeyLimitsErrors];

export type UpdateKeyLimitsResponses = {
    200: SuccessResponse;
};

export type UpdateKeyLimitsResponse = UpdateKeyLimitsResponses[keyof UpdateKeyLimitsResponses];

export type GetKeyModelUsageData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/model-usage';
};

export type GetKeyModelUsageResponses = {
    200: KeyModelUsageResponse;
};

export type GetKeyModelUsageResponse = GetKeyModelUsageResponses[keyof GetKeyModelUsageResponses];

export type RemoveKeyModelLimitsData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
        /**
         * Model ID
         */
        model: string;
    };
    query?: never;
    url: '/keys/{id}/model-usage/{model}/limits';
};

export type RemoveKeyModelLimitsErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type RemoveKeyModelLimitsError = RemoveKeyModelLimitsErrors[keyof RemoveKeyModelLimitsErrors];

export type RemoveKeyModelLimitsResponses = {
    200: SuccessResponse;
};

export type RemoveKeyModelLimitsResponse = RemoveKeyModelLimitsResponses[keyof RemoveKeyModelLimitsResponses];

export type SetKeyModelLimitsData = {
    body: UpdateLimitsRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
        /**
         * Model ID
         */
        model: string;
    };
    query?: never;
    url: '/keys/{id}/model-usage/{model}/limits';
};

export type SetKeyModelLimitsErrors = {
    500: ErrorResponse;
};

export type SetKeyModelLimitsError = SetKeyModelLimitsErrors[keyof SetKeyModelLimitsErrors];

export type SetKeyModelLimitsResponses = {
    200: SuccessResponse;
};

export type SetKeyModelLimitsResponse = SetKeyModelLimitsResponses[keyof SetKeyModelLimitsResponses];

export type ResetKeyModelUsageData = {
    body: ResetUsageRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
        /**
         * Model ID
         */
        model: string;
    };
    query?: never;
    url: '/keys/{id}/model-usage/{model}/reset';
};

export type ResetKeyModelUsageErrors = {
    400: ErrorResponse;
    404: ErrorResponse;
    500: ErrorResponse;
};

export type ResetKeyModelUsageError = ResetKeyModelUsageErrors[keyof ResetKeyModelUsageErrors];

export type ResetKeyModelUsageResponses = {
    200: SuccessResponse;
};

export type ResetKeyModelUsageResponse = ResetKeyModelUsageResponses[keyof ResetKeyModelUsageResponses];

export type GetKeyModelsData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/models';
};

export type GetKeyModelsResponses = {
    200: KeyModelsResponse;
};

export type GetKeyModelsResponse = GetKeyModelsResponses[keyof GetKeyModelsResponses];

export type SetKeyModelsData = {
    body: SetKeyModelsRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/models';
};

export type SetKeyModelsErrors = {
    500: ErrorResponse;
};

export type SetKeyModelsError = SetKeyModelsErrors[keyof SetKeyModelsErrors];

export type SetKeyModelsResponses = {
    200: SuccessResponse;
};

export type SetKeyModelsResponse = SetKeyModelsResponses[keyof SetKeyModelsResponses];

export type GetKeyUsageData = {
    body?: never;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/usage';
};

export type GetKeyUsageErrors = {
    404: ErrorResponse;
};

export type GetKeyUsageError = GetKeyUsageErrors[keyof GetKeyUsageErrors];

export type GetKeyUsageResponses = {
    200: KeyUsageResponse;
};

export type GetKeyUsageResponse = GetKeyUsageResponses[keyof GetKeyUsageResponses];

export type ResetKeyUsageData = {
    body: ResetUsageRequest;
    path: {
        /**
         * Key ID
         */
        id: string;
    };
    query?: never;
    url: '/keys/{id}/usage/reset';
};

export type ResetKeyUsageErrors = {
    400: ErrorResponse;
    404: ErrorResponse;
    500: ErrorResponse;
};

export type ResetKeyUsageError = ResetKeyUsageErrors[keyof ResetKeyUsageErrors];

export type ResetKeyUsageResponses = {
    200: SuccessResponse;
};

export type ResetKeyUsageResponse = ResetKeyUsageResponses[keyof ResetKeyUsageResponses];

export type ListModelsAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models';
};

export type ListModelsAdminResponses = {
    200: ListModelsResponse;
};

export type ListModelsAdminResponse = ListModelsAdminResponses[keyof ListModelsAdminResponses];

export type AddModelData = {
    body: AddModelRequest;
    path?: never;
    query?: never;
    url: '/models';
};

export type AddModelErrors = {
    400: ErrorResponse;
    500: ErrorResponse;
};

export type AddModelError = AddModelErrors[keyof AddModelErrors];

export type AddModelResponses = {
    200: SuccessResponse;
};

export type AddModelResponse = AddModelResponses[keyof AddModelResponses];

export type ReorderModelsData = {
    body: ReorderModelsRequest;
    path?: never;
    query?: never;
    url: '/models/reorder';
};

export type ReorderModelsErrors = {
    500: ErrorResponse;
};

export type ReorderModelsError = ReorderModelsErrors[keyof ReorderModelsErrors];

export type ReorderModelsResponses = {
    200: SuccessResponse;
};

export type ReorderModelsResponse = ReorderModelsResponses[keyof ReorderModelsResponses];

export type DeleteModelData = {
    body?: never;
    path: {
        /**
         * Model ID
         */
        id: string;
    };
    query?: never;
    url: '/models/{id}';
};

export type DeleteModelErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type DeleteModelError = DeleteModelErrors[keyof DeleteModelErrors];

export type DeleteModelResponses = {
    200: SuccessResponse;
};

export type DeleteModelResponse = DeleteModelResponses[keyof DeleteModelResponses];

export type UpdateModelData = {
    body: UpdateModelRequest;
    path: {
        /**
         * Model ID
         */
        id: string;
    };
    query?: never;
    url: '/models/{id}';
};

export type UpdateModelErrors = {
    404: ErrorResponse;
    500: ErrorResponse;
};

export type UpdateModelError = UpdateModelErrors[keyof UpdateModelErrors];

export type UpdateModelResponses = {
    200: SuccessResponse;
};

export type UpdateModelResponse = UpdateModelResponses[keyof UpdateModelResponses];

export type DeleteOauthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth';
};

export type DeleteOauthErrors = {
    500: ErrorResponse;
};

export type DeleteOauthError = DeleteOauthErrors[keyof DeleteOauthErrors];

export type DeleteOauthResponses = {
    200: SuccessResponse;
};

export type DeleteOauthResponse = DeleteOauthResponses[keyof DeleteOauthResponses];

export type ExchangeOauthCodeData = {
    body: ExchangeCodeRequest;
    path?: never;
    query?: never;
    url: '/oauth/exchange';
};

export type ExchangeOauthCodeErrors = {
    400: ErrorResponse;
};

export type ExchangeOauthCodeError = ExchangeOauthCodeErrors[keyof ExchangeOauthCodeErrors];

export type ExchangeOauthCodeResponses = {
    200: SuccessResponse;
};

export type ExchangeOauthCodeResponse = ExchangeOauthCodeResponses[keyof ExchangeOauthCodeResponses];

export type StartOauthFlowData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/start-flow';
};

export type StartOauthFlowResponses = {
    200: OAuthUrlResponse;
};

export type StartOauthFlowResponse = StartOauthFlowResponses[keyof StartOauthFlowResponses];

export type GetOauthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/status';
};

export type GetOauthStatusResponses = {
    200: OAuthStatusResponse;
};

export type GetOauthStatusResponse = GetOauthStatusResponses[keyof GetOauthStatusResponses];

export type GetSubscriptionUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth/usage';
};

export type GetSubscriptionUsageErrors = {
    401: ErrorResponse;
    502: ErrorResponse;
};

export type GetSubscriptionUsageError = GetSubscriptionUsageErrors[keyof GetSubscriptionUsageErrors];

export type GetSubscriptionUsageResponses = {
    200: SubscriptionUsageResponse;
};

export type GetSubscriptionUsageResponse = GetSubscriptionUsageResponses[keyof GetSubscriptionUsageResponses];

export type DeleteUsageHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/usage-history';
};

export type DeleteUsageHistoryErrors = {
    500: ErrorResponse;
};

export type DeleteUsageHistoryError = DeleteUsageHistoryErrors[keyof DeleteUsageHistoryErrors];

export type DeleteUsageHistoryResponses = {
    200: SuccessResponse;
};

export type DeleteUsageHistoryResponse = DeleteUsageHistoryResponses[keyof DeleteUsageHistoryResponses];

export type GetUsageHistoryByKeyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period: 24h, 7d, or 30d
         */
        period?: string;
    };
    url: '/usage-history/by-key';
};

export type GetUsageHistoryByKeyResponses = {
    200: KeyBreakdownResponse;
};

export type GetUsageHistoryByKeyResponse = GetUsageHistoryByKeyResponses[keyof GetUsageHistoryByKeyResponses];

export type GetUsageHistoryByModelData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period: 24h, 7d, or 30d
         */
        period?: string;
    };
    url: '/usage-history/by-model';
};

export type GetUsageHistoryByModelResponses = {
    200: ModelBreakdownResponse;
};

export type GetUsageHistoryByModelResponse = GetUsageHistoryByModelResponses[keyof GetUsageHistoryByModelResponses];

export type GetUsageHistoryTimeseriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period: 24h, 7d, or 30d
         */
        period?: string;
    };
    url: '/usage-history/timeseries';
};

export type GetUsageHistoryTimeseriesResponses = {
    200: TimeseriesResponse;
};

export type GetUsageHistoryTimeseriesResponse = GetUsageHistoryTimeseriesResponses[keyof GetUsageHistoryTimeseriesResponses];
